# ImageNet数据集TDA超参数配置
# 
# 此文件包含通过论文4.3节报告的消融研究找到的最优超参数
# 这些设置为ImageNet验证集实现了缓存质量和多样性之间的最佳平衡

# --- 正缓存配置 ---
# 实现高置信度伪标签存储(论文3.2节)
positive:
  enabled: True          # 启用正缓存进行有信心的预测
  shot_capacity: 3       # 每类最大k-shot样本数(图4显示k=3最优)
                        # 更高容量导致噪声积累
                        # 更低容量减少表示多样性
  alpha: 2.0            # 残差比率(缓存预测的权重因子)
                        # 论文报告最优值为2.0(相比Tip-Adapter的1.0)
                        # 给适配特征相对CLIP特征更高权重
  beta: 5.0             # 锐度比率(控制相似度函数陡峭程度)
                        # 用于适配函数A(z) = α * exp(-β(1-z))
                        # 更高β = 更锐化的相似度权重

# --- 负缓存配置 ---  
# 实现负伪标签以减少噪声(论文3.2节)
negative:
  enabled: True          # 启用负缓存进行不确定预测
  shot_capacity: 2       # 每类最大k̃-shot样本数(图4显示k̃=2最优)
                        # 负缓存对shot数量更敏感
                        # 更大容量导致更嘈杂的伪标签
  alpha: 0.117          # 负贡献的残差比率
                        # 比正α小得多以避免过度修正
  beta: 1.0             # 负相似度计算的锐度比率
  
  # 基于熵的样本选择(公式5)
  # 条件γ(f_test): τ_l < H(f_test @ W_c^T) < τ_h
  entropy_threshold:
    lower: 0.2          # τ_l: 下熵阈值
    upper: 0.5          # τ_h: 上熵阈值
                        # 只使用中等不确定的样本
                        # 避免高置信度(低熵)和非常不确定(高熵)的样本
  
  # 负伪标签阈值(公式4)  
  # L̂_n = -𝟙[p_l < P(Q_n)] 其中p_l是掩码阈值
  mask_threshold:
    lower: 0.03         # p_l: 负标签的概率阈值
    upper: 1.0          # 上界(通常不使用，设为1.0)
                        # 概率>0.03的类别得到负标签(-1)
                        # 概率≤0.03的类别得到中性标签(0)